set-option global tabstop 4
set-option global aligntab true
set-option global indentwidth 0

set-option -add global ui_options ncurses_assistant=none
set-option -add global ui_options terminal_set_title=false

hook global BufCreate '.*' %{
	add-highlighter buffer/show-whitespaces show-whitespaces -lf ' ' -spc ' ' -tab '│'
	add-highlighter buffer/wrap wrap
	add-highlighter buffer/matching show-matching
	add-highlighter buffer/col80 column 80 Col80
}

#map global normal ';' ':'

source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak" noload

source "%val{config}/smarttab.kak"
source "%val{config}/ruler.kak"
source "%val{config}/lsp.kak"
source "%val{config}/theme.kak"
source "%val{config}/powerline.kak"

#plug "andreyorst/fzf.kak"
#map global normal <c-p> ': fzf-mode<ret>'

#plug "crizan/kak-rainbower"
#hook global WinCreate .* rainbow-enable-window

plug "lePerdu/kakboard" config %{
	hook global WinCreate .* kakboard-enable
}

plug "alexherbo2/auto-pairs.kak" config %{
	enable-auto-pairs

	# Custom hooks for the <> pairing that don't interfere with normal usage
	hook global InsertKey '<a-,>' %{
		execute-keys '<'
		handle-inserted-opening-pair '<' '>'
	}
	hook global InsertDelete '<' %{
		handle-deleted-opening-pair '<' '>'
	}
}

plug "andreyorst/kaktree" config %{
	hook global WinSetOption filetype=kaktree %{
		remove-highlighter buffer/numbers
		remove-highlighter buffer/matching
		remove-highlighter buffer/wrap
		remove-highlighter buffer/show-whitespaces
		disable-ruler buffer
	}
	kaktree-enable
} defer kaktree %{
	set-option global kaktree_dir_icon_close ''
	set-option global kaktree_dir_icon_open 'ﱮ'
	set-option global kaktree_file_icon ''
	set-option global kaktree_indentation 1
	set-option global kaktree_show_help false
	map global normal <c-n> ': kaktree-toggle<ret>'
}
