set-option global tabstop 4
set-option global aligntab true
set-option global indentwidth 0

set-option -add global ui_options ncurses_assistant=none

add-highlighter global/ show-whitespaces -lf ' ' -spc ' ' -tab '│'
add-highlighter global/ wrap

#map global normal ';' ':'

source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak" noload

source "%val{config}/ruler.kak"
source "%val{config}/lsp.kak"
source "%val{config}/theme.kak"
source "%val{config}/powerline.kak"

#plug "andreyorst/fzf.kak"
#map global normal <c-p> ': fzf-mode<ret>'

#plug "crizan/kak-rainbower"
#hook global WinCreate .* rainbow-enable-window

plug "lePerdu/kakboard" config %{
	hook global WinCreate .* kakboard-enable
}
