add_newline = false

right_format = """$time"""

[directory]
truncation_length = 0
style = "cyan"
substitutions = { "/mnt/c" = "C:", "/mnt/d" = "D:", "/mnt/e" = "E:" }

[status]
disabled = false
format = "[$status ]($style)"

[username]
format = "[$user]($style)"
style_user = ""
show_always = true

[hostname]
format = "[@](#6272a4)[$hostname]($style) "
style = ""
ssh_only = false

[line_break]
disabled = false

[aws]
disabled = true

[time]
disabled = false
format = "[$time]($style)"
style = "bright-black"

[env_var.fish_private_mode]
format = "🎭"
